spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
spring:
  config:
    activate:
      on-profile: "qa"

loans:
  message: "Welcome to EazyBank loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "cyrano@eazybank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467
