spring:
  datasource:
   url: jdbc:mysql://localhost:3308/loansdb
   driver-class-name: com.mysql.jdbc.Driver
   username: root
   password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
